# Generated by Django 3.2.3 on 2021-05-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_date', models.DateTimeField(auto_now_add=True)),
                ('tweet_body', models.TextField()),
            ],
        ),
    ]
